name: vlt5_eval
channels:
  - conda-forge
dependencies:
  - python=3.8.3
  - pip
  - openjdk
  - pip:
    - torch==1.7.1
    - transformers==4.21.1
    - torchmetrics
    - git+https://github.com/google-research/bleurt@master
    - git+https://github.com/salaniz/pycocoevalcap.git
